swagger: "2.0"
info:
  version: "0.0.1"
  title: Services
# during dev, should point to your local machine
# basePath prefixes all resource paths 
basePath: /Services
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services:
    dbCache:
      provider: volos-cache-memory
      options:
        name: mycache
        ttl: 60000
paths:
  /recipes:
    # binds a127 app logic to a route
    x-swagger-router-controller: recipe
    x-a127-apply:
      dbCache: {}
    post:

      description: create a recipe
      summary: create a recipe
      # used as the method name of the controller
      operationId: createRecipe
      tags:
        - "Recipes"
      parameters:
        - name: body
          in: body
          description: requestbody
          required: true
          schema:
            $ref: "#/definitions/Recipe"

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Recipe"
        # responses may fall through to errors
        default:
          description: Error
  /users:
      # binds a127 app logic to a route
      x-swagger-router-controller: users
      x-a127-apply: {}
      post:

        description: create  login account
        summary: create  login account
        # used as the method name of the controller
        operationId: createLogin
        tags:
          - "Users"


        responses:
          "200":
            description: Success

          # responses may fall through to errors
          default:
            description: Error
# complex objects have schema definitions
  /testExtendModel:
      # binds a127 app logic to a route
      x-swagger-router-controller: test
      x-a127-apply:
        dbCache: {}
      post:

        description: test post
        summary: test post
        # used as the method name of the controller
        operationId: getTest
        tags:
          - "test"
        parameters:
          - name: method
            in: header
            description: test
            required: true
            type: string
            default: "DELETE"
          - name: body
            in: body
            description: requestbody
            required: true
            schema:
              $ref: "#/definitions/REMOTE_START"
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/Recipe"
          # responses may fall through to errors
          default:
            description: Error

definitions:
  REMOTE_COMMAND:
      discriminator: commandType
      properties:
        commandType:
          enum:
            - "REMOTE_DOOR_LOCK"
            - "REMOTE_DOOR_UNLOCK"
            - "REMOTE_START"
            - "REMOTE_HORNBLOW_LIGHTFLASH"
            - "PERSONAL_DATA_WIPE"
        credentials:
          type: "string"
        delay:
          type: "number"
          minimum: 0


      required:
        - commandType
        - credentials

  REMOTE_DOOR_LOCK:
      allOf:
        - $ref: "#/definitions/REMOTE_COMMAND"
      additionalProperties: false

  REMOTE_DOOR_UNLOCK:
      allOf:
        - $ref: "#/definitions/REMOTE_COMMAND"
      additionalProperties: false

  PERSONAL_DATA_WIPE:
      allOf:
        - $ref: "#/definitions/REMOTE_COMMAND"
      additionalProperties: false

  REMOTE_START:
    allOf:
      - $ref: "#/definitions/REMOTE_COMMAND"
      - properties:
          options:
            properties:
              mode:
                enum:
                  - "REMOTE_START"
                  - "REMOTE_STOP"
                  - "TEMP_FUEL_CHECK"
            required:
              - mode
        required:
          - options
        additionalProperties: false

  REMOTE_HORNBLOW_LIGHTFLASH:
    allOf:
      - $ref: "#/definitions/REMOTE_COMMAND"
      - properties:
          options:
            properties:
              mode:
                enum:
                  - "HORN_LIGHT"
                  - "HORN_ONLY"
                  - "LIGHT_ONLY"
            required:
              - mode
        required:
          - options
        additionalProperties: false
  Recipe:

    properties:
      id:
        type: number
        default: 0
      name:
        type: string
        default: "Source soup"
      category:
        $ref: "#/definitions/RecipeCategory"

      rank:
        type: string
        description: overall star rank
      recipeCountry:
            $ref: "#/definitions/Country"

  RecipeCategory:
      enum:
        - Soup
        - Entree
        - Salad
        - Dessert
  Country:
      type: string
      enum:
        - United States of America
        - Cambodia
        - India
        - Thai
        - Vietnam
        - China
      default: "United States of America"




